/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateRouteImport } from './routes/create'
import { Route as CreateIndexRouteImport } from './routes/create.index'
import { Route as CreateCaptureRouteImport } from './routes/create.capture'
import { Route as CreateDetailsRouteImport } from './routes/create.details'
import { Route as CreateImportRouteImport } from './routes/create.import'
import { Route as CreateProcessingRouteImport } from './routes/create.processing'
import { Route as CreateSuccessRouteImport } from './routes/create.success'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateIndexRoute = CreateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreateRoute,
} as any)
const CreateCaptureRoute = CreateCaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => CreateRoute,
} as any)
const CreateDetailsRoute = CreateDetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => CreateRoute,
} as any)
const CreateImportRoute = CreateImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => CreateRoute,
} as any)
const CreateProcessingRoute = CreateProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => CreateRoute,
} as any)
const CreateSuccessRoute = CreateSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CreateRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRouteWithChildren
  '/create/capture': typeof CreateCaptureRoute
  '/create/details': typeof CreateDetailsRoute
  '/create/import': typeof CreateImportRoute
  '/create/processing': typeof CreateProcessingRoute
  '/create/success': typeof CreateSuccessRoute
  '/create/': typeof CreateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create/capture': typeof CreateCaptureRoute
  '/create/details': typeof CreateDetailsRoute
  '/create/import': typeof CreateImportRoute
  '/create/processing': typeof CreateProcessingRoute
  '/create/success': typeof CreateSuccessRoute
  '/create': typeof CreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRouteWithChildren
  '/create/capture': typeof CreateCaptureRoute
  '/create/details': typeof CreateDetailsRoute
  '/create/import': typeof CreateImportRoute
  '/create/processing': typeof CreateProcessingRoute
  '/create/success': typeof CreateSuccessRoute
  '/create/': typeof CreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/create/capture'
    | '/create/details'
    | '/create/import'
    | '/create/processing'
    | '/create/success'
    | '/create/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create/capture'
    | '/create/details'
    | '/create/import'
    | '/create/processing'
    | '/create/success'
    | '/create'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/create/capture'
    | '/create/details'
    | '/create/import'
    | '/create/processing'
    | '/create/success'
    | '/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/': {
      id: '/create/'
      path: '/'
      fullPath: '/create/'
      preLoaderRoute: typeof CreateIndexRouteImport
      parentRoute: typeof CreateRoute
    }
    '/create/capture': {
      id: '/create/capture'
      path: '/capture'
      fullPath: '/create/capture'
      preLoaderRoute: typeof CreateCaptureRouteImport
      parentRoute: typeof CreateRoute
    }
    '/create/details': {
      id: '/create/details'
      path: '/details'
      fullPath: '/create/details'
      preLoaderRoute: typeof CreateDetailsRouteImport
      parentRoute: typeof CreateRoute
    }
    '/create/import': {
      id: '/create/import'
      path: '/import'
      fullPath: '/create/import'
      preLoaderRoute: typeof CreateImportRouteImport
      parentRoute: typeof CreateRoute
    }
    '/create/processing': {
      id: '/create/processing'
      path: '/processing'
      fullPath: '/create/processing'
      preLoaderRoute: typeof CreateProcessingRouteImport
      parentRoute: typeof CreateRoute
    }
    '/create/success': {
      id: '/create/success'
      path: '/success'
      fullPath: '/create/success'
      preLoaderRoute: typeof CreateSuccessRouteImport
      parentRoute: typeof CreateRoute
    }
  }
}

interface CreateRouteChildren {
  CreateCaptureRoute: typeof CreateCaptureRoute
  CreateDetailsRoute: typeof CreateDetailsRoute
  CreateImportRoute: typeof CreateImportRoute
  CreateProcessingRoute: typeof CreateProcessingRoute
  CreateSuccessRoute: typeof CreateSuccessRoute
  CreateIndexRoute: typeof CreateIndexRoute
}

const CreateRouteChildren: CreateRouteChildren = {
  CreateCaptureRoute: CreateCaptureRoute,
  CreateDetailsRoute: CreateDetailsRoute,
  CreateImportRoute: CreateImportRoute,
  CreateProcessingRoute: CreateProcessingRoute,
  CreateSuccessRoute: CreateSuccessRoute,
  CreateIndexRoute: CreateIndexRoute,
}

const CreateRouteWithChildren =
  CreateRoute._addFileChildren(CreateRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
